import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import Footer from "./components/Footer/Footer";
// import SpreadSection from "./components/SpreadSection.jsx/SpreadSection";
// import MUISection from "./components/MUISection/MUISection";
import ModernNav from "./components/ModernNavigation/MordernNav.jsx";

import LandingSection from "./components/LandingSection/LandingSection";
import Slider from "./components/AntComponents/AntCarousel.js";
import FeatureIcon from "./components/Atoms/FeatureIcon.jsx";
import { Col, Row } from "antd";

// const customTheme = createTheme({
//   palette: {
//     secondary: {
//       main: "#fff",
//     },
//   },
// });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ResponsiveAppBar /> */}
      <ModernNav />
      {/* <AntdNavigation /> */}
      <LandingSection />
      {/* <DatePicker /> */}
      <Slider />
      {/* <div className="flex flex-wrap w-10/12 gap-2"> */}
      <div className="w-8/12 pl-4 pt-2 text-3xl">
        <h2 className="font-black text-sky-500 ">How we work</h2>
      </div>
      <Row className="md:w-8/12  px-2 pb-8 mx-auto" gutter={[8, 4]}>
        {[
          {
            title: "Respect",
            color: "#f5ec3e",
            description:
              "We demand trust, integrity and mutual respect from ourselves and others. ",
            imgSrc: "/Icons/HowWeWork/respect.png",
          },
          {
            title: "Qaulity",
            color: "#f5ec3e",
            description:
              "We set high standards for the quality of all our activities.",
            imgSrc: "/Icons/HowWeWork/quality.png",
          },
          {
            title: "Commitment",
            color: "#f5ec3e",
            description:
              "We are fully involved in every project, the hard work and success of our employees gives us and our clients the greatest satisfaction.  ",
            imgSrc: "/Icons/HowWeWork/commitment.png",
          },
          {
            title: "Responsibility",
            color: "#f5ec3e",
            description:
              "We take responsibility for our work and the environment in which we operate.",
            imgSrc: `/Icons/HowWeWork/responsibility.png`,
          },
          {
            title: "Effectiveness",
            color: "#f5ec3e",
            description:
              "We are ambitious and consistently strive to achieve our goals",
            imgSrc: `/Icons/HowWeWork/responsibility.png`,
          },
          {
            title: "Professionalism",
            color: "#f5ec3e",
            description:
              "We constantly improve our qualifications and are willing to share our experience",
            imgSrc: `/Icons/HowWeWork/responsibility.png`,
          },
        ].map((feature) => (
          <FeatureIcon
            key={feature.title}
            caption={feature.caption}
            title={feature.title}
            color={feature.color}
            description={feature.description}
            imgSrc={feature.imgSrc}
          />
        ))}
      </Row>

      {/* </div> */}
      <div className="py-12  bg-gray-200">
        <h2
          style={{
            color: "linear-gradient(to right, #553c9a 45%, #ee4b2b)",
          }}
          className="mx-auto text-2xl w-10/12"
        >
          Meet our Team
        </h2>
      </div>
      <Footer />
    </div>
  );
}
