import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ResponsiveAppBar from "./components/HeroSection";
import Footer from "./components/Footer/Footer";
import SpreadSection from "./components/SpreadSection.jsx/SpreadSection";
import MUISection from "./components/MUISection/MUISection";
import ModernNav from "./components/ModernNavigation/MordernNav.jsx";
import { ThemeProvider } from "@emotion/react";
import { createTheme } from "@mui/material/styles";
import LandingSection from "./components/LandingSection/LandingSection";
import ServicesCard from "./components/ServicesCard/ServicesCard.jsx";

const customTheme = createTheme({
  palette: {
    secondary: {
      main: "#fff",
    },
  },
});

export default function Home() {
  return (
    <ThemeProvider theme={customTheme}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <ResponsiveAppBar /> */}
        <ModernNav />
        <LandingSection />

        <div className="py-12  bg-gray-200">
          <h2
            style={{ color: "linear-gradient(to right, #553c9a 45%, #ee4b2b)" }}
            className="text-3xl pl-12 py-4"
          >
            Seven Streams News
          </h2>
          <div className="flex flex-col mx-auto w-8/12 gap-2">
            {[
              "https://images.yen.com.gh/images/2fffb2680db922de.jpg",
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4TnmkTaFMrQNqBn3V7Ftn1_aZFph54w0NCZ0Azm-G3PmB2a6d2HUEm9kGFuTozjzj93o&usqp=CAU",
              "https://4f2s6b1l8e0pe5cqg3beg6b2-wpengine.netdna-ssl.com/wp-content/uploads/2019/08/shutterstock_1025490817-1.jpg",
            ].map((item) => (
              <ServicesCard key={item} imgSrc={item} />
            ))}
          </div>
        </div>

        <Footer />
      </div>
    </ThemeProvider>
  );
}
